on:
  push:
  pull_request:
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt-get install libnfc-dev python3-dev swig cmake
          cmake -DCMAKE_INSTALL_PREFIX=~/.local . && make install -j4
          python -c "import nfc; print(nfc.__version__)"
      
      
